{% set version = '1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rmallow
  version: {{ version|replace("-", "_") }}

source:
  fn: RMallow_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/RMallow_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RMallow/RMallow_{{ version }}.tar.gz
  sha256: 8e777accc78a3756e9cd68decbd6e8a44681ffd32dae692ce174bb8083aa0345

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-combinat
  run:
    - r-base
    - r-combinat

test:
  commands:
    - $R -e "library('RMallow')"           # [not win]
    - "\"%R%\" -e \"library('RMallow')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RMallow
  license: GPL (>= 2)
  summary: An EM algorithm to fit Mallows' Models to full or partial rankings, with or without
    ties.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
