{% set version = "1.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rmallow
  version: {{ version|replace("-", "_") }}

source:
  fn: RMallow_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/RMallow_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RMallow/RMallow_{{ version }}.tar.gz
  sha256: 92bde4b75ae7bb60aabe451607d15deca123d63847c09c1173398d73c818cae8

build:
  noarch: generic
  number: 4
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-combinat
  run:
    - r-base
    - r-combinat

test:
  commands:
    - $R -e "library('RMallow')"           # [not win]
    - "\"%R%\" -e \"library('RMallow')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RMallow
  license: GPL (>= 2)
  summary: An EM algorithm to fit Mallows' Models to full or partial rankings, with or without
    ties.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
