travis:
  secure:
    BINSTAR_TOKEN: R7JXRbJO32CyKjBuGjZkEt8L5NQutX6XbLyWoS6aAYA4keFtXaQR+wIhvymP0oWkS4Y7I1s7Qol1TSvl98gNaOOgXAwdyR2h96j/5cGWEC9733x+Z/67JnIsjCeApzf90OZ2duNVTQe3lDNmHHY8dcf2XUyRbNEhWdNtbTRn4S7aLwklFm/yeSySS06vUEm271FLYwclmXArSQYt6kCQkbEp13XWlfw2jgSoA6+B2x41/OsWpnA5mA/lPsWTPsRM/khRHbnG2NW+iwG3mB58CE7aGQpmIe2KE6ICF2VkIXVGi1IQWFiJm2Z9RrNiPGWcRFOdSlXg2K+LMF5n7YCoyhw5fPBxo0qhR5OMNpSjifwKOcg8V6hjXP1iPKsxg7mYxklOaScde+fNg2zu+3reeSwbaYkIoK1hwEv6snJfgNrhm2UxlLTH59rSNMfiZ2e9AAWKsdTo1ykryocyjEA3TSvRjB+RidI1qPpULXke3cDmcE20mDJvEQEoGOLtp/3vN4B3Fg48OvXFAyIaw96gfUi+ELJcVgnm0bU7FGsYgqVm6BzZd+mtQZOOkmxpf2CSDJmRrHeA6N2PhYHzBizD3I4OhG5le27aadZiCYsbuz1ukNIZHo2rBsxjWH8cnzi/IgvZn7Pr2npXeHeo57y4nm3/0l/De9+61q7wDkqbBxQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
