travis:
  secure:
    BINSTAR_TOKEN: Ni1RMhHxJCz+mFgGLe1Q1VD6qXolwjIgKxkNYME3OPETsQQXlfaZKOdcpJcPEyMOUH/+tUcEBxFTRoTjxjJ0j14VAB4v+tOyAMgaFZeJ8JHqqD27NY5t4RrE6Kl8TihUkAbygcTGWyS8aaINbC/Y5qLaV+6z5K7W6cuXMpOXIhlCyrHmAo58utjH5XvtZJgQZqD7PNgchHVG+X4Aq7E/qmrt7C+XxkDIZ1kT+7THO3boZNgJab4bSvONEzw9lXYHKL2ttTY76KefoxkZI/O/IcYX38Hry6196lNAIgU6f1zIXMGMbZJobQVX0LAwK+uaF3MEKYFPvGTtJqXy+WOdp7ukbOiBR69gQ/+Qft6lW6RrPJfxO+mg4NeWrmylmdWY2toowtNKqLPnhJCojbaKQh7V2+UQvhmYyelnOBxJdl6vU7QqVnPAn70lhAeL2AT177SQG9pUkvbaMFsYGRS3YQnlrYX5beSVKkl/rv0Iu8zAnJPai3JT3GvPtPsAwBGll7jBsTLE3L3xUVWdZUcXrixJaYBx70ljROWZ3C1OmID2K3NkWmsIsMxqrwZrfDvzenoRGKMNPEMou+QiQY+3IsurfydxfZCLSuNnehteNtnzq9gSWZmpuDjmJG+wgBKUae1m7q7MMGOKNKCmIxmrL5Inz1t2BnVeJr80BSO4d4w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
